title: EducOnto and EduKG - An Ontology and a Knowledge Graph for Higher Education

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
url:              https://nicolas-hbt.github.io/educ-ontokg/
baseurl:          https://nicolas-hbt.github.io/educ-ontokg/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicolas-hbt/educ-ontokg

# Google Analytics
google_analytics: G-LC085ZEKPS
