title: EducOnto and EduKG - An Ontology and a Knowledge Graph for Higher Education

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
url:              https://nicolas-hbt.github.io/educ-ontokg/
baseurl:          https://nicolas-hbt.github.io/educ-ontokg/

author:
  name:           'Nicolas Hubert'
  url:            https://twitter.com/nicolas_hubr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicolas-hbt/educ-ontokg

# Google Analytics
google_analytics: UA-234703790-1
